### ISSUE TITLE
Kopernicus Beta (0.2) issue with Linux

### ISSUE THREAD

**Issue by Seloune** [BryceSchroeder/Kopernicus#54] opened 2015-07-05 12:44 UTC
Hello!

Kopernicus Beta 0.1 doesn't work with my KSP 64 bits (fresh install) and ModuleManager 2.6.6 on LinuxMint 17.1 Rebecca 64bits.

If I install the plugin with Outer Planets Mod 1.7.1, the planets do not appear. I tested with Kopernicus Pre-Alpha Release 9 with OPM 1.7.1, the plugin and the OPM work fine.

Any chance to have a compatibility for the futur version? :)

Thanks you very much for you work and sorry for my bad english.

Take care, 
Seloune.

**Comment by ThomasKerman** [comment] 2015-07-05 13:40
We need your KSPRoot/Logs folder and your Player.log. ;)

2015-07-05 14:44 GMT+02:00 Seloune <notifications@github.com>:

**Comment by Seloune** [comment] 2015-07-06 10:08
KSP doesn't create the output-log.txt on Linux system. I have just this KSP.log:

https://www.dropbox.com/s/6uo85dinb1a0mp4/KSP.log?dl=0

**Comment by Tellion** [comment] 2015-07-06 14:20
Your player log is under /home/username/.config/unity3d/Squad/Kerbal Space Program

**Comment by ThomasKerman** [comment] 2015-07-06 15:23
OK, KSP.log shows, that it's a Kopernicus error. We need your KSPRoot/Logs folder

**Comment by Teknoman117** [comment] 2015-07-06 16:18
Okay well that error is with a Linq query.  My guess is that either HomeStar() is failing or the original star lookup failed, as any further query would cause an exception.  But yeah Kopernicus logs as before would be nice.

**Comment by Seloune** [comment] 2015-07-07 10:22
@Tellion : Oh yes, thanks you very much :) No I haven't nothing else installed (just Outer Planet Mod). I wanted recreate the problem with a KSP fresh Install.

http://imgur.com/a/OvewL

First picture with Kopernicus Alpha 0.0.9
Second picture with Kopernicus Beta 0.1

@ThomasKerman and Teknoman:

My KSPRoot/Logs :) :

https://www.dropbox.com/s/ze2udqzs1wmy4p6/Player.log?dl=0

**Comment by ThomasKerman** [comment] 2015-07-09 12:09
Could you please try it again with the newest Hotfix in https://github.com/BryceSchroeder/Kopernicus/tree/master/Distribution/GameData/Kopernicus/Plugins ?

**Comment by ThomasKerman** [comment] 2015-07-09 12:16
P.S. If it doesn't works, we **need** your KSPRoot/Logs folder as a .zip file. It contains the Kopernicus-logs, and if it's a Kopernicus-Issue, it will appear there

**Comment by Teknoman117** [comment] 2015-07-09 21:09
Well, we hope it shows up there lol

**Comment by Teknoman117** [comment] 2015-07-09 21:13
Either way I'll try it when I get home.  I develop on Linux almost exclusively anyways...

**Comment by Teknoman117** [comment] 2015-07-10 04:40
I was unable to reproduce the issue.  I downloaded the current version of Outer Planets Mod (1.7.1) and I used the current binary build of Kopernicus (0.2.2 - https://github.com/BryceSchroeder/Kopernicus/raw/master/Distribution/GameData/Kopernicus/Plugins/Kopernicus.dll).  

System Information

Kerbal Space Program - 1.0.4.0 (LinuxPlayer)
OS: Linux 3.19 ManjaroLinux 0.8.13 64bit
CPU: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz (8)
RAM: 16050
GPU: GeForce GTX 770/PCIe/SSE2 (4096MB)
SM: 30 (OpenGL 4.5 [4.5.0 NVIDIA 352.21])
RT Formats: ARGB32, Depth, ARGBHalf, RGB565, ARGB4444, ARGB1555, Default, DefaultHDR, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8

**Comment by Teknoman117** [comment] 2015-07-10 04:52
Please test again with the hot fix and upload a zip (or a .tar.gz) of the logs.  Otherwise I'll be closing this issue

**Comment by Seloune** [comment] 2015-07-10 08:11
Hey :)

No sorry, the update plugin doesn't work for me.

I call you my installation:

KSP 1.0.4, OPM 7.1 and your update Kopernicus plugin.
OS: LinuxMint 17.1 Rebecca

My KSP log: 

https://www.dropbox.com/s/139fsbc2plwyqye/KSP%20logs.7z?dl=0

**Comment by Teknoman117** [comment] 2015-07-10 16:40
Thomas, I don't think kopenicus started enough in his case to even generate logs.  Look - null reference system in Generate().

Actually, i wonder if this is partially the issue - Seloune, can you check the file permissions on your ksp folder (like "ls -lR ." from the KSP folder).  I wonder if the game doesn't have permission to generate the logs ... Unless there is a Log/ folder in your KSP root directory.  We implemented our own logger.

for instance - http://imgur.com/42OlLOdl.png

**Comment by ThomasKerman** [comment] 2015-07-10 16:59
No, null reference in Generate() will definitivly appear if there is an error in the Body-Loading queue, so we can't use it to determine where the issue occures. It doesn't have to be related to logger-issues.

**Comment by Teknoman117** [comment] 2015-07-10 18:20
Depends on how early it fails.  Until the first body begins to load, Flush() never gets called.  If it fails before the first flush(), Logs/ would be generated but nothing would be populated.  Either way - Seloune, can you please check for the existance of that folder.  Its not any KSP standard logg file, we wrote our own because Debug.Log sucks for large systems.

**Comment by Seloune** [comment] 2015-07-10 18:48
Yes with the right permission, the folder was generated :)

https://www.dropbox.com/s/zdb82qsurt6dhvy/Logs.7z?dl=0

**Comment by Teknoman117** [comment] 2015-07-10 18:57
@Thomas, can you look into this?  Seems to be something wrong with PQS in
Body.PostApply().  Only PQS-less body are loading successfully.  Damn I
wish exceptions included line numbers...

- Nathan

**Comment by ThomasKerman** [comment] 2015-07-10 19:13
@Seloune did you edit you settings.cfg, especially the PQS-Presets? (If you don't understand what I'm trying to say, just uplaod your settings.cfg, and I will check it. :))
@Teknoman117 for reference, take a look at this comment: https://github.com/BryceSchroeder/Kopernicus/commit/abca6c0dc9af4fa78b03b21d0afcab55fa7e3c19 Kopernicus adds presets for the PQSCache (to fix a debug warning), but I've hardcoded the names, so if he changed them, It would throw a NRE.

**Comment by Seloune** [comment] 2015-07-11 07:53
@ThomasKerman: Yeah amazing Thomas, very good job! I always used to copy my setting.cfg a KSP to another KSP instance... If I delete my setting.cfg and regenerate another fresh file, the plugin (Kopernicus Beta 0.2) and OPM work fine!

Thanks you very much :)

Ready to close.

**Closed** 2015-07-11 09:04 UTC
